[package]
name = "game"
version = "0.1.0"
authors = ["0918nobita"]
edition = "2018"

[dependencies]
ash = "0.32"
env_logger = "0.8"
log = "0.4"
once_cell = "1.8"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"

[features]
default = ["validation_layers"]
validation_layers = []
