name: Build

on: push

jobs:
  build-native:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1
      - name: Restore NuGet packages
        run: dotnet restore
      - name: Build solution
        run: msbuild NovelGame.sln

  build-nodejs:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
        working-directory: ds-compiler
      - name: Build
        run: npm run build
        working-directory: ds-compiler
