name: Lint

on: push

jobs:
  lint:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install clang-format
        run: |
          sudo apt update
          sudo apt install clang-format
      - name: Install cpplint
        run: pip install cpplint
      - name: Execute cpplint
        run: make lint
