name: Lint

on: push

jobs:
  lint-native:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install clang-format
        run: |
          sudo apt update
          sudo apt install clang-format
      - name: Install cpplint
        run: pip install cpplint
      - name: Execute cpplint
        run: make lint

  lint-nodejs:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
        working-directory: ds-compiler
      - name: Lint
        run: npm run lint
        working-directory: ds-compiler
