name: Lint

on: push

jobs:
  lint:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
        working-directory: ds-compiler
      - name: Lint
        run: npm run lint
        working-directory: ds-compiler
