name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install libraries
        run: |
          sudo add-apt-repository ppa:graphics-drivers/ppa
          sudo apt update
          sudo apt install libvulkan-dev libgtest-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
          git clone https://github.com/glfw/glfw
          cd glfw
          mkdir -p build
          cd build
          cmake -DBUILD_SHARED_LIBS=OFF -DGLFW_VULKAN_STATIC=ON ..
          make
          ls -la
      - name: Build
        run: make -j
      - name: Run tests
        run: ./test
