name: Test

on: push

jobs:
  test:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
        working-directory: ds-compiler
      - name: Run tests
        run: npm run test
        working-directory: ds-compiler
