name: Test

on: push

jobs:
  test-native:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libglfw3-dev libvulkan-dev nlohmann-json3-dev g++-10
      - name: Setup C++ compiler
        run: |
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 1
          g++ --version
      - name: Install Google Test
        run: |
          curl -OL https://github.com/google/googletest/archive/release-1.10.0.tar.gz
          tar -zxvf release-1.10.0.tar.gz
          mkdir -p googletest-release-1.10.0/build
          cd googletest-release-1.10.0/build
          cmake ..
          sudo make install
      - name: Build
        run: make
      - name: Run tests
        run: ./bin/test

  test-nodejs:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
        working-directory: ds-compiler
      - name: Run tests
        run: npm run test
        working-directory: ds-compiler
